export type League = {  league_id: number;
  league_name: string;
  year: number;
  is_fim: boolean;
  offseason: boolean;
  team_limit: number;
  team_starts: number;
  team_size_limit: number;
  weekly_starts?: number;
};