/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LeaguesLeagueIdImport } from './routes/leagues/$leagueId'
import { Route as DraftsDraftIdImport } from './routes/drafts/_.$draftId'

// Create Virtual Routes

const OffseasonDraftsLazyImport = createFileRoute('/offseasonDrafts')()
const EventDataLazyImport = createFileRoute('/eventData')()
const IndexLazyImport = createFileRoute('/')()
const LeaguesIndexLazyImport = createFileRoute('/leagues/')()
const LeaguesLeagueIdWaiversLazyImport = createFileRoute(
  '/leagues/$leagueId/waivers',
)()
const LeaguesLeagueIdScoresLazyImport = createFileRoute(
  '/leagues/$leagueId/scores',
)()
const LeaguesLeagueIdRostersLazyImport = createFileRoute(
  '/leagues/$leagueId/rosters',
)()
const LeaguesLeagueIdRankingsLazyImport = createFileRoute(
  '/leagues/$leagueId/rankings',
)()
const LeaguesLeagueIdAvailableLazyImport = createFileRoute(
  '/leagues/$leagueId/available',
)()
const DraftsDraftIdScoresLazyImport = createFileRoute(
  '/drafts/$draftId/scores',
)()
const DraftsDraftIdLeagueWeeksLazyImport = createFileRoute(
  '/drafts/$draftId/leagueWeeks',
)()

// Create/Update Routes

const OffseasonDraftsLazyRoute = OffseasonDraftsLazyImport.update({
  path: '/offseasonDrafts',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/offseasonDrafts.lazy').then((d) => d.Route),
)

const EventDataLazyRoute = EventDataLazyImport.update({
  path: '/eventData',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/eventData.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LeaguesIndexLazyRoute = LeaguesIndexLazyImport.update({
  path: '/leagues/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/leagues/index.lazy').then((d) => d.Route))

const LeaguesLeagueIdRoute = LeaguesLeagueIdImport.update({
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueIdWaiversLazyRoute = LeaguesLeagueIdWaiversLazyImport.update(
  {
    path: '/waivers',
    getParentRoute: () => LeaguesLeagueIdRoute,
  } as any,
).lazy(() =>
  import('./routes/leagues/$leagueId/waivers.lazy').then((d) => d.Route),
)

const LeaguesLeagueIdScoresLazyRoute = LeaguesLeagueIdScoresLazyImport.update({
  path: '/scores',
  getParentRoute: () => LeaguesLeagueIdRoute,
} as any).lazy(() =>
  import('./routes/leagues/$leagueId/scores.lazy').then((d) => d.Route),
)

const LeaguesLeagueIdRostersLazyRoute = LeaguesLeagueIdRostersLazyImport.update(
  {
    path: '/rosters',
    getParentRoute: () => LeaguesLeagueIdRoute,
  } as any,
).lazy(() =>
  import('./routes/leagues/$leagueId/rosters.lazy').then((d) => d.Route),
)

const LeaguesLeagueIdRankingsLazyRoute =
  LeaguesLeagueIdRankingsLazyImport.update({
    path: '/rankings',
    getParentRoute: () => LeaguesLeagueIdRoute,
  } as any).lazy(() =>
    import('./routes/leagues/$leagueId/rankings.lazy').then((d) => d.Route),
  )

const LeaguesLeagueIdAvailableLazyRoute =
  LeaguesLeagueIdAvailableLazyImport.update({
    path: '/available',
    getParentRoute: () => LeaguesLeagueIdRoute,
  } as any).lazy(() =>
    import('./routes/leagues/$leagueId/available.lazy').then((d) => d.Route),
  )

const DraftsDraftIdScoresLazyRoute = DraftsDraftIdScoresLazyImport.update({
  path: '/drafts/$draftId/scores',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/drafts/$draftId/scores.lazy').then((d) => d.Route),
)

const DraftsDraftIdLeagueWeeksLazyRoute =
  DraftsDraftIdLeagueWeeksLazyImport.update({
    path: '/drafts/$draftId/leagueWeeks',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/drafts/$draftId/leagueWeeks.lazy').then((d) => d.Route),
  )

const DraftsDraftIdRoute = DraftsDraftIdImport.update({
  path: '/drafts/$draftId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/eventData': {
      id: '/eventData'
      path: '/eventData'
      fullPath: '/eventData'
      preLoaderRoute: typeof EventDataLazyImport
      parentRoute: typeof rootRoute
    }
    '/offseasonDrafts': {
      id: '/offseasonDrafts'
      path: '/offseasonDrafts'
      fullPath: '/offseasonDrafts'
      preLoaderRoute: typeof OffseasonDraftsLazyImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdImport
      parentRoute: typeof rootRoute
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/drafts//$draftId': {
      id: '/drafts//$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof DraftsDraftIdImport
      parentRoute: typeof rootRoute
    }
    '/drafts/$draftId/leagueWeeks': {
      id: '/drafts/$draftId/leagueWeeks'
      path: '/drafts/$draftId/leagueWeeks'
      fullPath: '/drafts/$draftId/leagueWeeks'
      preLoaderRoute: typeof DraftsDraftIdLeagueWeeksLazyImport
      parentRoute: typeof rootRoute
    }
    '/drafts/$draftId/scores': {
      id: '/drafts/$draftId/scores'
      path: '/drafts/$draftId/scores'
      fullPath: '/drafts/$draftId/scores'
      preLoaderRoute: typeof DraftsDraftIdScoresLazyImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueId/available': {
      id: '/leagues/$leagueId/available'
      path: '/available'
      fullPath: '/leagues/$leagueId/available'
      preLoaderRoute: typeof LeaguesLeagueIdAvailableLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
    '/leagues/$leagueId/rankings': {
      id: '/leagues/$leagueId/rankings'
      path: '/rankings'
      fullPath: '/leagues/$leagueId/rankings'
      preLoaderRoute: typeof LeaguesLeagueIdRankingsLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
    '/leagues/$leagueId/rosters': {
      id: '/leagues/$leagueId/rosters'
      path: '/rosters'
      fullPath: '/leagues/$leagueId/rosters'
      preLoaderRoute: typeof LeaguesLeagueIdRostersLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
    '/leagues/$leagueId/scores': {
      id: '/leagues/$leagueId/scores'
      path: '/scores'
      fullPath: '/leagues/$leagueId/scores'
      preLoaderRoute: typeof LeaguesLeagueIdScoresLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
    '/leagues/$leagueId/waivers': {
      id: '/leagues/$leagueId/waivers'
      path: '/waivers'
      fullPath: '/leagues/$leagueId/waivers'
      preLoaderRoute: typeof LeaguesLeagueIdWaiversLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
  }
}

// Create and export the route tree

interface LeaguesLeagueIdRouteChildren {
  LeaguesLeagueIdAvailableLazyRoute: typeof LeaguesLeagueIdAvailableLazyRoute
  LeaguesLeagueIdRankingsLazyRoute: typeof LeaguesLeagueIdRankingsLazyRoute
  LeaguesLeagueIdRostersLazyRoute: typeof LeaguesLeagueIdRostersLazyRoute
  LeaguesLeagueIdScoresLazyRoute: typeof LeaguesLeagueIdScoresLazyRoute
  LeaguesLeagueIdWaiversLazyRoute: typeof LeaguesLeagueIdWaiversLazyRoute
}

const LeaguesLeagueIdRouteChildren: LeaguesLeagueIdRouteChildren = {
  LeaguesLeagueIdAvailableLazyRoute: LeaguesLeagueIdAvailableLazyRoute,
  LeaguesLeagueIdRankingsLazyRoute: LeaguesLeagueIdRankingsLazyRoute,
  LeaguesLeagueIdRostersLazyRoute: LeaguesLeagueIdRostersLazyRoute,
  LeaguesLeagueIdScoresLazyRoute: LeaguesLeagueIdScoresLazyRoute,
  LeaguesLeagueIdWaiversLazyRoute: LeaguesLeagueIdWaiversLazyRoute,
}

const LeaguesLeagueIdRouteWithChildren = LeaguesLeagueIdRoute._addFileChildren(
  LeaguesLeagueIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/eventData': typeof EventDataLazyRoute
  '/offseasonDrafts': typeof OffseasonDraftsLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/leagues': typeof LeaguesIndexLazyRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/drafts/$draftId/leagueWeeks': typeof DraftsDraftIdLeagueWeeksLazyRoute
  '/drafts/$draftId/scores': typeof DraftsDraftIdScoresLazyRoute
  '/leagues/$leagueId/available': typeof LeaguesLeagueIdAvailableLazyRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/rosters': typeof LeaguesLeagueIdRostersLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
  '/leagues/$leagueId/waivers': typeof LeaguesLeagueIdWaiversLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/eventData': typeof EventDataLazyRoute
  '/offseasonDrafts': typeof OffseasonDraftsLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/leagues': typeof LeaguesIndexLazyRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/drafts/$draftId/leagueWeeks': typeof DraftsDraftIdLeagueWeeksLazyRoute
  '/drafts/$draftId/scores': typeof DraftsDraftIdScoresLazyRoute
  '/leagues/$leagueId/available': typeof LeaguesLeagueIdAvailableLazyRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/rosters': typeof LeaguesLeagueIdRostersLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
  '/leagues/$leagueId/waivers': typeof LeaguesLeagueIdWaiversLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/eventData': typeof EventDataLazyRoute
  '/offseasonDrafts': typeof OffseasonDraftsLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/leagues/': typeof LeaguesIndexLazyRoute
  '/drafts//$draftId': typeof DraftsDraftIdRoute
  '/drafts/$draftId/leagueWeeks': typeof DraftsDraftIdLeagueWeeksLazyRoute
  '/drafts/$draftId/scores': typeof DraftsDraftIdScoresLazyRoute
  '/leagues/$leagueId/available': typeof LeaguesLeagueIdAvailableLazyRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/rosters': typeof LeaguesLeagueIdRostersLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
  '/leagues/$leagueId/waivers': typeof LeaguesLeagueIdWaiversLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eventData'
    | '/offseasonDrafts'
    | '/leagues/$leagueId'
    | '/leagues'
    | '/drafts/$draftId'
    | '/drafts/$draftId/leagueWeeks'
    | '/drafts/$draftId/scores'
    | '/leagues/$leagueId/available'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/rosters'
    | '/leagues/$leagueId/scores'
    | '/leagues/$leagueId/waivers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eventData'
    | '/offseasonDrafts'
    | '/leagues/$leagueId'
    | '/leagues'
    | '/drafts/$draftId'
    | '/drafts/$draftId/leagueWeeks'
    | '/drafts/$draftId/scores'
    | '/leagues/$leagueId/available'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/rosters'
    | '/leagues/$leagueId/scores'
    | '/leagues/$leagueId/waivers'
  id:
    | '__root__'
    | '/'
    | '/eventData'
    | '/offseasonDrafts'
    | '/leagues/$leagueId'
    | '/leagues/'
    | '/drafts//$draftId'
    | '/drafts/$draftId/leagueWeeks'
    | '/drafts/$draftId/scores'
    | '/leagues/$leagueId/available'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/rosters'
    | '/leagues/$leagueId/scores'
    | '/leagues/$leagueId/waivers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  EventDataLazyRoute: typeof EventDataLazyRoute
  OffseasonDraftsLazyRoute: typeof OffseasonDraftsLazyRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRouteWithChildren
  LeaguesIndexLazyRoute: typeof LeaguesIndexLazyRoute
  DraftsDraftIdRoute: typeof DraftsDraftIdRoute
  DraftsDraftIdLeagueWeeksLazyRoute: typeof DraftsDraftIdLeagueWeeksLazyRoute
  DraftsDraftIdScoresLazyRoute: typeof DraftsDraftIdScoresLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  EventDataLazyRoute: EventDataLazyRoute,
  OffseasonDraftsLazyRoute: OffseasonDraftsLazyRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRouteWithChildren,
  LeaguesIndexLazyRoute: LeaguesIndexLazyRoute,
  DraftsDraftIdRoute: DraftsDraftIdRoute,
  DraftsDraftIdLeagueWeeksLazyRoute: DraftsDraftIdLeagueWeeksLazyRoute,
  DraftsDraftIdScoresLazyRoute: DraftsDraftIdScoresLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/eventData",
        "/offseasonDrafts",
        "/leagues/$leagueId",
        "/leagues/",
        "/drafts//$draftId",
        "/drafts/$draftId/leagueWeeks",
        "/drafts/$draftId/scores"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/eventData": {
      "filePath": "eventData.lazy.tsx"
    },
    "/offseasonDrafts": {
      "filePath": "offseasonDrafts.lazy.tsx"
    },
    "/leagues/$leagueId": {
      "filePath": "leagues/$leagueId.tsx",
      "children": [
        "/leagues/$leagueId/available",
        "/leagues/$leagueId/rankings",
        "/leagues/$leagueId/rosters",
        "/leagues/$leagueId/scores",
        "/leagues/$leagueId/waivers"
      ]
    },
    "/leagues/": {
      "filePath": "leagues/index.lazy.tsx"
    },
    "/drafts//$draftId": {
      "filePath": "drafts/_.$draftId.tsx"
    },
    "/drafts/$draftId/leagueWeeks": {
      "filePath": "drafts/$draftId/leagueWeeks.lazy.tsx"
    },
    "/drafts/$draftId/scores": {
      "filePath": "drafts/$draftId/scores.lazy.tsx"
    },
    "/leagues/$leagueId/available": {
      "filePath": "leagues/$leagueId/available.lazy.tsx",
      "parent": "/leagues/$leagueId"
    },
    "/leagues/$leagueId/rankings": {
      "filePath": "leagues/$leagueId/rankings.lazy.tsx",
      "parent": "/leagues/$leagueId"
    },
    "/leagues/$leagueId/rosters": {
      "filePath": "leagues/$leagueId/rosters.lazy.tsx",
      "parent": "/leagues/$leagueId"
    },
    "/leagues/$leagueId/scores": {
      "filePath": "leagues/$leagueId/scores.lazy.tsx",
      "parent": "/leagues/$leagueId"
    },
    "/leagues/$leagueId/waivers": {
      "filePath": "leagues/$leagueId/waivers.lazy.tsx",
      "parent": "/leagues/$leagueId"
    }
  }
}
ROUTE_MANIFEST_END */
